### ISSUE TITLE
Self-referencing class creates duplicate identifier

### ISSUE THREAD

**Issue by daveriedstra** [jburzynski/TypeGen#8]
```C#
public class MyClass {
    public MyClass MyMember { get; set; }
}
```
generates typescript file `my-class.ts`:
```typescript
import { MyClass } from "./my-class";
export class MyClass {
    myMember: MyClass;
}
```
which gives typescript error `[ts] Import declaration conflicts with local declaration of 'MyClass'`. It's easy enough to delete the self-referential import, but it will get recreated the next time TypeGen is run.

(This is in TypeGen v1.5.5)

**Comment by jburzynski** [comment]
Should be fixed in v1.5.6 (just uploaded to NuGet).

**Comment by daveriedstra** [comment]
That fixed it in 2 of 3 cases, but there's still one case where the generated class file is attempting to import itself. Here's an overview of the C# model file, maybe something will stand out.

```C#
// usings ... 
namespace NS.NS
{
  // more usings

  [ExportTsClass]
  public class MyClass : BaseClass<Guid>
  {
    public MyClass MyMember { get; set; }
    [TsType(TsType.String)]
    public Guid? MyMemberId { get; set; }

    public List<MyJoinClass> MyJoins { get; set; }

    // a pile of other members with other types (ie, not MyClass or MyJoinClass)
  }

  public class MyJoinClass
  {
    public MyClass Class { get; set; }
    [TsType(TsType.String)]
    public Guid ClassId { get; set; }

    public MyOtherClass OtherClass { get; set; }
    [TsType(TsType.String)]
    public Guid OtherClassId { get; set; }
  }
}
```

**Comment by jburzynski** [comment]
I wasn't able to replicate the error based on this example. When I tried it, `MyClass` only imports `MyJoinClass` (because I don't have properties of any other types in `MyClass`).

Which class is importing itself in your case? Is it `MyClass` or `MyJoinClass`?

Also, have your tried deleting the project's `bin` folder? I found that it helps sometimes, although I'm not sure in which cases exactly.

**Comment by daveriedstra** [comment]
Interesting. It's `MyClass` that's importing itself. I tried removing the `bin` folder but it didn't fix the issue. Annotating `MyClass.MyMember` with `[TsIgnore]` removes the problematic import (but of course, also the property, which we need).

**Comment by jburzynski** [comment]
Just to be on the safe side - can you check if `TypeGen` or `TypeGen -h` shows version 1.5.6?

Also, I've noticed that in my case there's an error when a class inherits from a base class which has `Guid` as a generic parameter (it can't recognize the `Guid` type). Can you make sure that it isn't this scenario that's causing an error in your case? I.e. can you make sure that in the file content there actually is an 'import' that's importing the class itself?

I've just tried to generate my example (based on your case) with `TypeGen.exe` downloaded and unpacked [directly from nuget.org](https://www.nuget.org/api/v2/package/TypeGen/1.5.6) and it seems to work fine, so I can't really see where the problem is. Maybe you can also try to use the `TypeGen.exe` from direct NuGet download to rule out this possibility as well?

Other than that I'm not really sure what can be causing this error.

**Comment by daveriedstra** [comment]
ack I'm so sorry, I forgot to update the `.exe` to 1.5.6! Updating it fixed everything.

With `Guid` I have a `<custom-head>` which imports a simple typescript `Guid` class. This has been working well for some time now.
```typescript
export class Guid extends String {}
```

This is fixed so I'll close it. Thanks for your help and sorry again.

**Comment by jburzynski** [comment]
No problem, glad I could help!
